---
- name: ensure the keystone database is configured
  ini_file:
    dest: /etc/keystone/keystone.conf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - section: database
      option: connection
      value: "{{ openstack_keystone_database_url }}"
  notify:
    - restart apache2
    - sync keystone database
  tags:
    - keystone
    - configuration

- name: ensure the fernet token provider is configured
  ini_file:
    dest: /etc/keystone/keystone.conf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - section: token
      option: provider
      value: fernet
  notify:
    - restart apache2
  tags:
    - keystone
    - configuration
