---
- name: ensure the OpenStack client is installed
  apt:
    name: python-openstackclient
    state: present
  tags:
    - openstack

- name: ensure pip is installed
  apt:
    name: python-pip
    state: present
  tags:
    - openstack

- name: ensure shade is installed for OpenStack -> ansible integration
  pip:
    name: shade
    state: present
  tags:
    - openstack
