---
- name: ensure the OpenStack RabbitMQ user exists
  rabbitmq_user:
    user: '{{ openstack_rabbitmq_username }}'
    password: '{{ openstack_rabbitmq_password }}'
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
  tags:
    - rabbitmq
