---
dependencies:
  - role: openstack-common
  - role: memcached
  - role: rabbitmq
  - role: mysql
    vars:
      mysql_root_password: "{{ openstack_mysql_root_password }}"
  - role: apache2
  - role: etcd
