- name: set the hostname
  hostname:
    name: "{{ hostname | default(inventory_hostname) }}"
  tags: network

- name: make the hostname permanent
  copy:
    content: "{{ hostname | default(inventory_hostname) }}.{{ vlans[primary_vlan].domain_name }}"
    dest: /etc/hostname
    owner: root
    group: root
    mode: 0644
  tags: network

- name: remove the extra loopback interface
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.1\.1'
    state: absent
  tags: network

- name: ensure the localhost entry is configured
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1'
    line: '127.0.0.1 localhost {{ hostname | default(inventory_hostname) }}'
    state: present
  tags: network

- name: ensure required packages are installed
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - resolvconf
    - vlan
  tags: network

- name: ensure the vlan module is loaded at boot
  lineinfile:
    dest: /etc/modules
    regexp: '^8021q'
    line: '8021q'
    state: present
  tags: network

- name: ensure the vlan module is loaded
  modprobe:
    name: 8021q
    state: present

- name: configure network interfaces
  template:
    src: 'etc/network/interfaces.j2'
    dest: '/etc/network/interfaces.ansible'
    owner: root
    group: root
    mode: 0644
  tags: network
