---
- name: ensure mysql is configured properly for openstack
  template:
    src: etc/mysql/mariadb.conf.d/99-openstack.cnf.j2
    dest: /etc/mysql/mariadb.conf.d/99-openstack.cnf
    owner: mysql
  notify:
    - restart mysql
  tags:
    - mysql

- meta: flush_handlers
