---
- name: ensure mysql is installed
  apt:
    name: mariadb-server
    state: present
  tags:
    - mysql

- name: ensure mysql is running
  service:
    name: mysql
    state: started
  tags:
    - mysql

- name: update mysql root password
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
    priv: "*.*:ALL,GRANT"
  with_items:
    - 127.0.0.1
    - ::1
    - localhost
    - '%'
  tags:
    - mysql

- name: create .my.cnf file with root password credentials
  template:
    src: root/my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    mode: 0600
  tags:
    - mysql

- name: ensure anonymous user does not exist
  mysql_user:
    user: ""
    host_all: yes
    state: absent
  tags:
    - mysql

- name: remove the test database
  mysql_db:
    db: test
    state: absent
  tags:
    - mysql
