---
openstack_keystone_database_url: "mysql+pymysql://{{ openstack_keystone_database_username }}:{{ openstack_keystone_database_password }}@{{ openstack_database_host }}/{{ openstack_keystone_database_name }}"
