---
- name: ensure the required packages are installed
  apt:
    name: python-pymysql
    state: present
  tags:
    - mysql

- name: ensure mysql is configured properly for openstack
  template:
    src: etc/mysql/mariadb.conf.d/99-openstack.cnf.j2
    dest: /etc/mysql/mariadb.conf.d/99-openstack.cnf
    owner: mysql
  notify:
    - restart mysql
  tags:
    - mysql
